apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-atd-workflow
  labels:
    app.kubernetes.io/name: my-atd-workflow
    kubernetes.azure.com/generator: devhub
  namespace: test-atd-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-atd-workflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-atd-workflow
    spec:
      containers:
        - name: my-atd-workflow
          image: tftestacr.azurecr.io/image-workflow-1738172546973:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: my-atd-workflow-config
            - secretRef:
                name: secret-ref
                optional: true
          livenessProbe:
            tcpSocket:
              port: 8000
          readinessProbe:
            tcpSocket:
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
            successThreshold: 1
            initialDelaySeconds: 3
          startupProbe:
            tcpSocket:
              port: 8000
            periodSeconds: 1
            timeoutSeconds: 3
            failureThreshold: 1
            successThreshold: 1
            initialDelaySeconds: 5
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
                - SYS_PTRACE
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: my-atd-workflow
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: my-atd-workflow